DarkRP.createEntityGroup("Güvenlik Birimleri", TEAM_EMNIYETAMIRI, TEAM_POLIS, TEAM_POHAMIR, TEAM_POHDOKTOR, TEAM_POHNISANCI, TEAM_POH, TEAM_BASKANKORUMASI, TEAM_MAYOR)

DarkRP.createEntityGroup("SideRP Bankası", TEAM_BANKACI, TEAM_BGUVENLIK)